### PR TITLE
UG Screenshots 

### PR DESCRIPTION
**Pull request by kavxya**
#154 #161 #164

### CODE REVIEW

**Review by cheehongw — COMMENTED** [review]
image

 `exit - minimize - expand` will look different on a different OS. 
 
at the risk of adding too many redundant info, perhaps we can further annotate on the image that these 3 things will be different on a different OS?

**Comment by cheehongw** [comment]
Also, image

**Review by cheehongw — COMMENTED** [review]
image 

The hyperlinks don't seem complete. Also why would cs2102 demonstrations lead to google?

use links like (this is the cs2103 lect link):
> https://nus-sg.zoom.us/j/92307270969?pwd=VVMvNWFPWFpyVHRIcXR0VkJlNkg0dz09

and maybe some dummy looking google hangouts link for cs2102

**Review by reignnz — APPROVED** [review]
Screenshots look good!

**Pull request merged**
